// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ggysbqedithjbzldcpry.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdneXNicWVkaXRoamJ6bGRjcHJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAxMzA2MDgsImV4cCI6MjA1NTcwNjYwOH0.YDeYHp7L8TVzXnvO2WCY0-z2bX9oRFLFbZXXgkYGYW0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);